# Generated by Django 2.2.6 on 2019-11-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_extends',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('bdate', models.DateField()),
                ('myfile', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('product_mage', models.ImageField(blank=True, upload_to='product/')),
                ('price', models.IntegerField()),
                ('Productname', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Upload_date', models.DateField()),
                ('status', models.CharField(default='sell', max_length=15)),
                ('catogory', models.CharField(choices=[('Books', 'Books'), ('Stationary', 'Stationary'), ('Household_supplies', 'Household_supplies'), ('Furnitures', 'Furnitures'), ('Sport-item', 'Sport-item'), ('Electronic-item', 'Electronic-item'), ('Bags_and_Luggage', 'Bags_and_Luggage')], default='Books', max_length=30)),
                ('payment_mode', models.CharField(choices=[('mode1', 'Phone-pay'), ('mode2', 'Google-pay'), ('mode3', 'Paytm'), ('mode4', 'Cash')], default='mode4', max_length=20)),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='payment_mode/')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.AuthUser')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Product')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.AuthUser')),
            ],
        ),
    ]
