# Generated by Django 2.2.6 on 2020-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catogory',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Household_supplies', 'Household_supplies'), ('Furnitures', 'Furnitures'), ('Sport-item', 'Sport-item'), ('Electronic-item', 'Electronic-item'), ('Bags_and_Luggage', 'Bags_and_Luggage')], default='Books', max_length=30),
        ),
    ]
