# Generated by Django 2.2.6 on 2020-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='current', max_length=50),
        ),
    ]
