# Generated by Django 2.2.6 on 2020-08-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_mage',
            new_name='product_image',
        ),
    ]
