# Generated by Django 2.2.6 on 2020-08-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200813_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_mage',
        ),
    ]
